using System.IO;
using System.Net;
using System.Security;
using System.Text;
using System.Web;
using ModMyFactory.Helpers;
using ModMyFactory.Web.AuthenticationApi;

namespace ModMyFactory.Web
{
    enum AuthenticationResult
    {
        Success,
        Failed,
        EmailAuthenticationRequired,
    }

    static class ApiAuthentication
    {
        const string LoginPage = "https://auth.factorio.com/api-login";

        /// <summary>
        /// Logs in at the api.
        /// </summary>
        /// <param name="username">The username.</param>
        /// <param name="password">The users password.</param>
        /// <param name="emailAuthenticationCode">Optional. The e-mail authentication code required for two-factor login.</param>
        /// <param name="info">Out. The login token generated by the server and the users name, or the server error.</param>
        /// <returns>Returns the result of the login attempt.</returns>
        public static AuthenticationResult LogIn(string username, SecureString password, string emailAuthenticationCode, out AuthenticationInfo info)
        {
            info = null;

            var builder = new StringBuilder();
            builder.Append("api_version=6&require_game_ownership=true");
            builder.Append("&username=").Append(HttpUtility.UrlEncode(username));
            if (!string.IsNullOrEmpty(emailAuthenticationCode))
                builder.Append("&email_authentication_code=").Append(HttpUtility.UrlEncode(emailAuthenticationCode));
            builder.Append("&password=");

            string part1 = builder.ToString();
            int part1Length = Encoding.UTF8.GetByteCount(part1);

            byte[] passwordBytes = SecureStringHelper.SecureStringToBytes(password);
            string part2 = HttpUtility.UrlEncode(passwordBytes);

            byte[] content = new byte[part1Length + part2.Length];
            Encoding.UTF8.GetBytes(part1, 0, part1.Length, content, 0);
            Encoding.UTF8.GetBytes(part2, 0, part2.Length, content, part1Length);

            try
            {
                string document = WebHelper.GetDocument(LoginPage, content);
                if (string.IsNullOrWhiteSpace(document)) return AuthenticationResult.Failed;

                info = JsonHelper.Deserialize<AuthenticationInfo>(document);
                if ((info == null) || string.IsNullOrWhiteSpace(info.Token) || string.IsNullOrWhiteSpace(info.Username))
                    return AuthenticationResult.Failed;

                return AuthenticationResult.Success;
            }
            catch (WebException ex) when (ex.Status == WebExceptionStatus.ProtocolError)
            {
                // The server reports login errors (wrong credentials, 2FA required, ...) as an HTTP error
                // with a JSON body of the form { "error": "...", "message": "..." }.
                info = ReadErrorResponse(ex.Response);
                if (info?.Error == "email-authentication-required")
                    return AuthenticationResult.EmailAuthenticationRequired;

                return AuthenticationResult.Failed;
            }
            finally
            {
                SecureStringHelper.DestroySecureByteArray(content);
            }
        }

        private static AuthenticationInfo ReadErrorResponse(WebResponse response)
        {
            if (response == null) return null;

            try
            {
                using (var stream = response.GetResponseStream())
                {
                    if (stream == null) return null;
                    using (var reader = new StreamReader(stream, Encoding.UTF8))
                    {
                        string document = reader.ReadToEnd();
                        if (string.IsNullOrWhiteSpace(document)) return null;
                        return JsonHelper.Deserialize<AuthenticationInfo>(document);
                    }
                }
            }
            catch
            {
                return null;
            }
            finally
            {
                response.Close();
            }
        }
    }
}
